build_pyoptsparse.sh

This accounts for the way pyOptSparse v2.1.0 switched from single quotes in their setup.py to double quotes, breaking the patch. v2.1.0 is also the default version of pyOptSparse used now.

Fixed patching for pyOptSparse v2.1.0

---

build_pyoptsparse.sh

conda install some 64 bit compilers.
These installs cause problems for installing Metis. But since the build script installs Metis before ParOpt, and these compiler installs are placed after the Metis install and before the ParOpt install.
Updated to default to the latest version of Pyoptsparse which supports ParOpt and does not have bugs with PQSP.

Added compiler installs needed to build paropt

---

build_pyoptsparse.sh

Turned off warnings for implicit function declarations, which were being treated as errors by the new compiler versions.
Resolves #7

Fixed building with Xcode12

---

README.md
build_pyoptsparse.sh

A subdirectory with a unique name is now created to work in (perform downloads and builds). This directory is removed if the build is successful, unless the -d switch is used.
SNOPT_DIR is converted to an absolute path since a relative path might be invalid in the new working dir. The SNOPT_DIR structure is also checked to determine whether the top level dir is referenced or the `src` subdir. Without this second step, the pyOptSparse build would have silently ignored SNOPT if it didn't see `snoptc.f`.
Resolves #9

Create a temporary working dir and double-check SNOPT dir layout

---

build_pyoptsparse.sh

The https://www.coin-or.org/ web site has been down on multiple occasions.
To make the script more reliable for use in CI, download the Ipopt releases from github.

get Ipopt release from github, which is more reliable than coin-or.org

---

README.md
build_pyoptsparse.sh

The following changes were made:
ParOpt-specific:
- Compiler installation is only attempted if a Travis build is detected
- `mpicxx` availability is added as a dependency
- Cython is pip-installed
Other areas:
- Basic compiler functionality is pretested for each of the C, C++, and FORTRAN compilers
- If a "system" Python installation is being used instead of a personal/virtual, confirmation is requested to proceed (skipped on Travis)
- Script won't continue if Python 3.x is not detected
- `numpy` is pip-installed prior to the pyOptSparse build
- The script detects the number of cores in the system, and does a parallel build using 50% (if there's more than one)
- Options added to skip the compiler and python tests
- A message about setting LD_LIBRARY_PATH or DYLD_LIBRARY_PATH is displayed …

Multiple fixes and updates

---

README.md
build_pyoptsparse.sh

When using HSL for the linear solver, the script had been relying on the filename and relative location of the HSL source tar file. The new `-t` option now lets the user specify any tar file in any accessible location.

Add -t option to specify tar file for HSL

---

build_pyoptsparse.sh

The latest code from MUMPS wouldn't build correctly, so the script was changed to pull from the latest stable branches of METIS, MUMPS, and IPOPT, rather than master. Now using version 3.13 of IPOPT instead of 3.12.

Pull from latest stable branches for metis, mumps, and ipopt

---

build_pyoptsparse.sh

MUMPS stable/2.1 was broken by new commits 5/14/2021
go back to MUMPS stable/2.0
also add some echos to make the log easier to parse

back up to MUMPS stable/2.0

---

build_pyoptsparse.sh

Older versions of bash didn't recognize the ${OPTARG^^} syntax to capitalize the value of an environment variable.

Fixed -l switch to work with older versions of bash

---

build_pyoptsparse.sh

Updated version of PR #30 making the fix conditional on GCC version:
```
-fallow-argument-mismatch is added to address issues building with GCC >= 10, as recommended in the thread here https://github.com/coin-or/coinbrew/issues/47
and/or here: https://github.com/coin-or-tools/ThirdParty-Mumps/issues/4
```
- Resolves #29
None
None

Add arg to MUMPS configuration for GCC >= 10

---

build_pyoptsparse.py

See OpenMDAO/OpenMDAO#2611 and https://github.com/pypa/setuptools/pull/3505
There is an [issue ](https://github.com/pypa/setuptools/issues/3532)on the `setuptools` repo to correct the issue, but as yet no indication that it will be fixed.
`setuptools` is a dependency in pyoptsparse's  [environment.xml](https://github.com/mdolab/pyoptsparse/blob/main/.github/environment.yml#L11) (which this script doesn't use, but is part of the recommended [install process](https://mdolab-pyoptsparse.readthedocs-hosted.com/en/latest/install.html#install))
This fix just makes sure an appropriate version is installed per the noted deprecation.

setuptools<65

---

build_pyoptsparse.py
build_pyoptsparse.sh

Set in both `build_pyoptsparse.py` and `build_pyoptsparse.sh`

Set IPOPT_DIR for pyOptSparse>=2.9.0

---

.github/workflows/test_workflow.yml

Add a GitHub workflow to test the build script on  push or pull request events for the master branch
- The `v1.2` build does not support `ParOpt` so MPI is not installed for that build.
- Secrets are used to provide access to `SNOPT` and/or `HSL` source code.
- There is some logic to test different linear solvers (e.g. `HSL`), but it's not exercised at this time.
- The `v1.2` build does not pass the `IPOPT` tests when using the default linear solver, so the `--no-ipopt` option is exercised.
- Tests are pulled from the `pyoptsparse` repo. 
- The repo is already cloned to a temp directory then deleted in the build process, but it's fast/easy/transparent to re-clone.
- I have thus far been unable to get the script working on the macos image, so it is left for future work.

Add a GitHub test workflow

---

.github/workflows/test_workflow.yml
build_pyoptsparse.py

Fixes the following issues:
- Older version of `setuptools` are incompatible with the recently released Python 3.12:
- Only install old version of `setuptools` for Python older than 3.12 (if necessary)
- If version of `setuptools` is changed, revert back to previously installed version
- Versions of `paropt` older than `v2.1.3` are incompatible with the recently released Cython 3.0:
- Changed to use paropt [v2.1.4](https://github.com/smdogroup/paropt/releases/tag/v2.1.4)
- The build flags for OSX were changed to those specified in [Makefile.in.info](https://github.com/smdogroup/paropt/blob/6aed60a9b241c57de498cea95b25e232eca9e91a/Makefile.in.info#L26)
- Incorporated the workflow updates from PR #53
- Since updates are infrequent, I have added a cron trigger to run the test suite once a …

Fixed issues with setuptools and paropt

---

.github/workflows/test_workflow.yml

Updates to the test workflow:
- use more current versions of Python, NumPy, SciPy and pyOptSparse as the baseline for testing
- do not post alerts for audit failures when testing the oldest supported versions

Update baseline test environment

---

.github/workflows/test_workflow.yml

- cut the time limit from 60 minutes to 30 minutes (which is still overkill)
- add a no-MPI job
- update the versions of the `checkout`, `setup-miniconda` and `slack` actions
- change miniconda to only use the `conda-forge` channel
- display the environment before and after running the `build_pyoptsparse` script
- run the tests from the version of the  `mdolab` repository that match the build
- add a timeout to the tests so a hung test is killed
- only send a message to slack if testing fails
- Resolves #
None
None

Update test  workflow

---

.github/workflows/test_workflow.yml
build_pyoptsparse.py

This PR fixes several build issues when building pyOptSparse with Ipopt and HSL solvers.
The configuration logic for the Mumps and HSL builds was largely the same, so I refactored the common parts into a `get_common_solver_config_cmd` function in order to remove duplication; YMMV on whether this is a good change or not.
This function sets up the arguments for the configure command and in particular:
1. Checks to see if `-lm` needs to be explicitly included. I based this check on whether the OS was Linux or not; this is probably not the most reliable approach and probably merits changing. (It also probably doesn't hurt to just always include `-lm`?)
2. If the compiler is identified as Apple Clang the `--disable-openmp` flag is provided. It's possible to build with OpenMP support, but I …

Fix HSL build issues

---

.github/workflows/test_workflow.yml

- added inputs to `workflow_dispatch` trigger to enable running and debugging a specific build
- updated baseline versions of Python, Numpy and Scipy
- changed MacOS baseline job to use MacOS 13 (latest is now ARM64)
- attempted a MacOS ARM build (unsucessfully, so commented out)
- added steps to enable debugging with tmate
- Resolves #
None
None

Updated test workflow

---

.github/workflows/test_workflow.yml

Using `ensurepip`  in the test workflow is resulting in pip version 22.3.1 which has a security vulnerability:
```
Found 1 known vulnerability in 1 package
Name Version ID             Fix Versions
---- ------- -------------- ------------
pip  22.3.1  PYSEC-2023-228 23.3
```
Removing `ensurepip`  results in using pip version 24.0, which does not have the vulnerability:
```
pip                       24.0               pyhd8ed1ab_0    conda-forge
```
Since the pip version is not really germane to the tests, the `ensurepip` call has been removed.
- Resolves #
None
None

Removed ensurepip from test workflow

---

.github/workflows/test_workflow.yml

A follow up to PR #67
Installation of `gettext` from `conda-forge` is still causing `pip` to be downgraded from 24.0 to 22.3, which has a security vulnerability:
```
Found 1 known vulnerability in 1 package
Name Version ID             Fix Versions
---- ------- -------------- ------------
pip  22.3.1  PYSEC-2023-228 23.3
```
`gettext` is a `pyoptsparse` dependency that is only needed when building the documentation.  Since that is out of scope for this package, and we are able to run the test suite without this dependency, it's installation has been removed.
Also:
- Enabled the MacOS ARM build in the test workflow, using `brew` to install compilers
- Added MacOS specific directories to find meson build logs
- Resolves #
None
None

Remove gettext from test workflow, add MacOS ARM build

---

.github/workflows/test_workflow.yml

- Disabled testing with ParOpt (see #69)
- Linked `gfortran` to `gfortran-13` on `macos-latest`
- Updated the "MacOS Baseline, forced build" job to use `macos-13` like the other "MacOS Baseline" job, and set it to use a working version of Xcode
- Resolves #
None
None

Updated workflow to get tests passing again

---

.github/workflows/test_workflow.yml
build_pyoptsparse.py

Updated version of pyOptSparse in the 'oldest' build of the test workflow.
The previous oldest version was broken by an update to setuptools.
- Resolves #
None
None

Updated version of pyOptSparse in the 'oldest' build of the test workflow

---

.github/workflows/test_workflow.yml

Change NumPy 1.x workflows to use Python  3.12, since Python  3.13 doesn't work with NumPy 1.x
- Resolves #
None
None

Change Numpy 1 workflows to use Python 3.12

---

.github/workflows/test_workflow.yml

After the incorporation of https://github.com/mdolab/pyoptsparse/pull/411, pyOptSparse now supports NumPy 2.x
This PR updates the `latest` jobs in the test matrix to test with NumPy 2.x and pyOptSparse>=2.13
- Resolves #
None
None

Updated test matrix to include NumPy 2.x and pyOptSparse>=2.13

---

build_pyoptsparse.py

Existing values for compiler options (CC, FC, CXX) will no longer be overridden if already set by the user. This was necessary for compatibility with brew compilers on MacOS.
Added --pip-cmd option.  If the user specifies --pip-cmd="uv pip", uv will be used to install the package. This is necessary for users who use uv for their environment management.
- Resolves #
None
None

Added some options for compatibility with brew and uv.

---

.github/workflows/test_workflow.yml
build_pyoptsparse.py

- cleaned up brew & MPI logic
- only test NumPy 2.x on ARM for MacOS
- Resolves #
None
None

update test workflow

---

.github/workflows/test_workflow.yml
build_pyoptsparse.py

A user was getting errors after running the script in a `conda` environment without first installing `SciPy` (see below). This was traced to the fact that `SciPy` was getting installed from `PyPI` (as a dependency of `pyoptsparse`) and that package seemed to be incompatible with the other packages  (e.g. `lapack`) that are installed from `conda-forge` by the script.
This change will install `NumPy` and `Scipy` from `conda-forge` before installing `pyoptsparse` if they are not installed, or re-install them from `conda-forge` if they were previously installed from `PyPI`.  This only happens when `conda` is enabled.
Tests were added to the GitHub workflow to exercise these scenarios.
Also:
- one of the tests in the matrix was updated to test with `SciPy 1.16`, which was released recently. …

Ensure NumPy/Scipy are installed from conda-forge if using conda
